spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/jobflowdb
spring.datasource.username=postgres
spring.datasource.password=anoushkaSQL

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
groq.api.key=${GROQ_API_KEY}
